/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnnxImport } from './routes/onnx'
import { Route as CameraImport } from './routes/camera'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OnnxRoute = OnnxImport.update({
  id: '/onnx',
  path: '/onnx',
  getParentRoute: () => rootRoute,
} as any)

const CameraRoute = CameraImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraImport
      parentRoute: typeof rootRoute
    }
    '/onnx': {
      id: '/onnx'
      path: '/onnx'
      fullPath: '/onnx'
      preLoaderRoute: typeof OnnxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/onnx': typeof OnnxRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/onnx': typeof OnnxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/onnx': typeof OnnxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/camera' | '/onnx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/camera' | '/onnx'
  id: '__root__' | '/' | '/about' | '/camera' | '/onnx'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CameraRoute: typeof CameraRoute
  OnnxRoute: typeof OnnxRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CameraRoute: CameraRoute,
  OnnxRoute: OnnxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/camera",
        "/onnx"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/camera": {
      "filePath": "camera.tsx"
    },
    "/onnx": {
      "filePath": "onnx.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
